-- Supabase SQL Editor 실행용 SQL
-- kstock_platform_data 테이블 및 인덱스, RLS 정책 정의

CREATE TABLE IF NOT EXISTS public.kstock_platform_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL,
    date_kst VARCHAR(10),
    status VARCHAR(20) DEFAULT 'published',
    published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 인덱스 생성 (조회 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_kstock_platform_data_key ON public.kstock_platform_data (key);
CREATE INDEX IF NOT EXISTS idx_kstock_platform_data_updated_at ON public.kstock_platform_data (updated_at DESC);

-- RLS (Row Level Security) 설정 및 정책 정의
ALTER TABLE public.kstock_platform_data ENABLE ROW LEVEL SECURITY;

-- 익명 사용자(anon) 및 서비스 롤(service_role) 전체 권한 허용 (서버 API 상호작용 목적)
CREATE POLICY "Allow public read access" ON public.kstock_platform_data
    FOR SELECT USING (true);

CREATE POLICY "Allow all access for service_role and authenticated" ON public.kstock_platform_data
    FOR ALL USING (true) WITH CHECK (true);
